[package]
edition = { workspace = true }
license = { workspace = true }
name = "minigu-transaction"
repository = { workspace = true }
version = { workspace = true }

[dependencies]
minigu-common = { workspace = true }

[lints]
workspace = true
